/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_marketplace_marketplace_add_parameter_0$schema = z.string()
const _deepseek_ai_dsh_marketplace_marketplace_add_result$schema = z.object({
  'packageName': z.string().readonly(),
  'restartRequired': z.boolean().readonly(),
})
const _deepseek_ai_dsh_marketplace_marketplace_beginOAuth_parameter_0$schema = z.object({
  'baseUrl': z.string().readonly(),
  'clientId': z.string().readonly(),
})
const _deepseek_ai_dsh_marketplace_marketplace_beginOAuth_result$schema = z.object({
  'flowId': z.string().readonly(),
  'authorizationUrl': z.string().readonly(),
})
const _deepseek_ai_dsh_marketplace_marketplace_catalog_result$schema = z.object({
  'repository': z.string().readonly(),
  'ref': z.string().readonly(),
  'plugins': z.array(z.object({
  'id': z.string().readonly(),
  'packageName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'version': z.string().readonly(),
  'dshVersion': z.string().readonly(),
  'placement': z.union([z.literal("before-web-app"), z.literal("after-web-app")]).readonly(),
  'artifact': z.object({
  'path': z.string().readonly(),
  'sha256': z.string().readonly(),
  'size': z.number().readonly(),
}).readonly(),
  'compatible': z.boolean().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_marketplace_marketplace_configure_parameter_0$schema = z.object({
  'baseUrl': z.string().readonly(),
  'repository': z.string().readonly(),
  'ref': z.string().readonly(),
  'token': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_marketplace_marketplace_configure_result$schema = z.object({
  'baseUrl': z.string().readonly(),
  'repository': z.string().readonly(),
  'ref': z.string().readonly(),
  'tokenConfigured': z.boolean().readonly(),
  'tokenWritable': z.boolean().readonly(),
  'authMode': z.union([z.literal("oauth"), z.literal("token"), z.literal("none")]).readonly(),
  'oauthClientId': z.string().readonly().optional(),
  'nativeRestartAvailable': z.boolean().readonly(),
  'installed': z.array(z.object({
  'packageName': z.string().readonly(),
  'specifier': z.string().readonly(),
  'version': z.string().readonly().optional(),
})).readonly(),
})
const _deepseek_ai_dsh_marketplace_marketplace_deletePackage_parameter_0$schema = z.string()
const _deepseek_ai_dsh_marketplace_marketplace_deletePackage_result$schema = z.object({
  'packageName': z.string().readonly(),
  'restartRequired': z.boolean().readonly(),
})
const _deepseek_ai_dsh_marketplace_marketplace_oauthStatus_parameter_0$schema = z.string()
const _deepseek_ai_dsh_marketplace_marketplace_oauthStatus_result$schema = z.union([z.object({
  'status': z.literal("pending").readonly(),
}), z.object({
  'status': z.literal("complete").readonly(),
}), z.object({
  'status': z.literal("failed").readonly(),
  'message': z.string().readonly(),
})])
const _deepseek_ai_dsh_marketplace_marketplace_refreshCatalog_result$schema = z.object({
  'repository': z.string().readonly(),
  'ref': z.string().readonly(),
  'plugins': z.array(z.object({
  'id': z.string().readonly(),
  'packageName': z.string().readonly(),
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'version': z.string().readonly(),
  'dshVersion': z.string().readonly(),
  'placement': z.union([z.literal("before-web-app"), z.literal("after-web-app")]).readonly(),
  'artifact': z.object({
  'path': z.string().readonly(),
  'sha256': z.string().readonly(),
  'size': z.number().readonly(),
}).readonly(),
  'compatible': z.boolean().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_marketplace_marketplace_repositories_result$schema = z.array(z.object({
  'id': z.number().readonly(),
  'path': z.string().readonly(),
  'name': z.string().readonly(),
  'defaultBranch': z.string().readonly().optional(),
}))
const _deepseek_ai_dsh_marketplace_marketplace_state_result$schema = z.object({
  'baseUrl': z.string().readonly(),
  'repository': z.string().readonly(),
  'ref': z.string().readonly(),
  'tokenConfigured': z.boolean().readonly(),
  'tokenWritable': z.boolean().readonly(),
  'authMode': z.union([z.literal("oauth"), z.literal("token"), z.literal("none")]).readonly(),
  'oauthClientId': z.string().readonly().optional(),
  'nativeRestartAvailable': z.boolean().readonly(),
  'installed': z.array(z.object({
  'packageName': z.string().readonly(),
  'specifier': z.string().readonly(),
  'version': z.string().readonly().optional(),
})).readonly(),
})

export const TYPERT = {
  package: '@shamcleren/dsh-plugin-marketplace',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@shamcleren/dsh-plugin-marketplace#marketplace/add',
      service: 'marketplace',
      namespace: 'marketplace',
      method: 'add',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'packageName',
          wire: 'packageName',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@shamcleren/dsh-plugin-marketplace#marketplace/add:packageName',
            schema: _deepseek_ai_dsh_marketplace_marketplace_add_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@shamcleren/dsh-plugin-marketplace/types#MarketplaceMutationResult',
        schema: _deepseek_ai_dsh_marketplace_marketplace_add_result$schema,
      },
      sourceLocation: {"file":"packages/marketplace/marketplace/src/index.ts","line":323,"column":9},
    },
    {
      id: '@shamcleren/dsh-plugin-marketplace#marketplace/beginOAuth',
      service: 'marketplace',
      namespace: 'marketplace',
      method: 'beginOAuth',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@shamcleren/dsh-plugin-marketplace/types#MarketplaceOAuthRequest',
            schema: _deepseek_ai_dsh_marketplace_marketplace_beginOAuth_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@shamcleren/dsh-plugin-marketplace/types#MarketplaceOAuthStart',
        schema: _deepseek_ai_dsh_marketplace_marketplace_beginOAuth_result$schema,
      },
      sourceLocation: {"file":"packages/marketplace/marketplace/src/index.ts","line":245,"column":9},
    },
    {
      id: '@shamcleren/dsh-plugin-marketplace#marketplace/catalog',
      service: 'marketplace',
      namespace: 'marketplace',
      method: 'catalog',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@shamcleren/dsh-plugin-marketplace/types#MarketplaceCatalogView',
        schema: _deepseek_ai_dsh_marketplace_marketplace_catalog_result$schema,
      },
      sourceLocation: {"file":"packages/marketplace/marketplace/src/index.ts","line":298,"column":9},
    },
    {
      id: '@shamcleren/dsh-plugin-marketplace#marketplace/configure',
      service: 'marketplace',
      namespace: 'marketplace',
      method: 'configure',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@shamcleren/dsh-plugin-marketplace/types#MarketplaceConfigureRequest',
            schema: _deepseek_ai_dsh_marketplace_marketplace_configure_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@shamcleren/dsh-plugin-marketplace/types#MarketplaceState',
        schema: _deepseek_ai_dsh_marketplace_marketplace_configure_result$schema,
      },
      sourceLocation: {"file":"packages/marketplace/marketplace/src/index.ts","line":278,"column":9},
    },
    {
      id: '@shamcleren/dsh-plugin-marketplace#marketplace/deletePackage',
      service: 'marketplace',
      namespace: 'marketplace',
      method: 'deletePackage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'packageName',
          wire: 'packageName',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@shamcleren/dsh-plugin-marketplace#marketplace/deletePackage:packageName',
            schema: _deepseek_ai_dsh_marketplace_marketplace_deletePackage_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@shamcleren/dsh-plugin-marketplace/types#MarketplaceMutationResult',
        schema: _deepseek_ai_dsh_marketplace_marketplace_deletePackage_result$schema,
      },
      sourceLocation: {"file":"packages/marketplace/marketplace/src/index.ts","line":344,"column":9},
    },
    {
      id: '@shamcleren/dsh-plugin-marketplace#marketplace/oauthStatus',
      service: 'marketplace',
      namespace: 'marketplace',
      method: 'oauthStatus',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'flowId',
          wire: 'flowId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@shamcleren/dsh-plugin-marketplace#marketplace/oauthStatus:flowId',
            schema: _deepseek_ai_dsh_marketplace_marketplace_oauthStatus_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@shamcleren/dsh-plugin-marketplace/types#MarketplaceOAuthStatus',
        schema: _deepseek_ai_dsh_marketplace_marketplace_oauthStatus_result$schema,
      },
      sourceLocation: {"file":"packages/marketplace/marketplace/src/index.ts","line":259,"column":3},
    },
    {
      id: '@shamcleren/dsh-plugin-marketplace#marketplace/refreshCatalog',
      service: 'marketplace',
      namespace: 'marketplace',
      method: 'refreshCatalog',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@shamcleren/dsh-plugin-marketplace/types#MarketplaceCatalogView',
        schema: _deepseek_ai_dsh_marketplace_marketplace_refreshCatalog_result$schema,
      },
      sourceLocation: {"file":"packages/marketplace/marketplace/src/index.ts","line":311,"column":9},
    },
    {
      id: '@shamcleren/dsh-plugin-marketplace#marketplace/repositories',
      service: 'marketplace',
      namespace: 'marketplace',
      method: 'repositories',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@shamcleren/dsh-plugin-marketplace#marketplace/repositories:result',
        schema: _deepseek_ai_dsh_marketplace_marketplace_repositories_result$schema,
      },
      sourceLocation: {"file":"packages/marketplace/marketplace/src/index.ts","line":268,"column":9},
    },
    {
      id: '@shamcleren/dsh-plugin-marketplace#marketplace/state',
      service: 'marketplace',
      namespace: 'marketplace',
      method: 'state',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@shamcleren/dsh-plugin-marketplace/types#MarketplaceState',
        schema: _deepseek_ai_dsh_marketplace_marketplace_state_result$schema,
      },
      sourceLocation: {"file":"packages/marketplace/marketplace/src/index.ts","line":222,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
